import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Edit3, Filter, History as HistoryIcon, Search, XCircle } from 'lucide-react';
import api from '@/services/api';
import { useToast } from '@/context/ToastContext';
import Select from '@/components/ui/Select';
import Input from '@/components/ui/Input';
import Button from '@/components/ui/Button';
import Spinner from '@/components/ui/Spinner';
import ConfirmDialog from '@/components/ui/ConfirmDialog';

export default function AttendanceHistory() {
  const { showToast } = useToast();
  const [sections,setSections]=useState([]); const [subjects,setSubjects]=useState([]); const [history,setHistory]=useState([]); const [loading,setLoading]=useState(false); const [edit,setEdit]=useState(null);
  const [filters,setFilters]=useState({section_id:'',subject_id:'',date_from:'',date_to:''});
  useEffect(()=>{Promise.all([api.get('/teacher/sections'),api.get('/teacher/subjects')]).then(([a,b])=>{setSections(a.data||[]);setSubjects(b.data||[])}).catch(()=>showToast('Failed to load filter options','error'));},[]);
  const search=async()=>{setLoading(true);try{const {data}=await api.get('/attendance',{params:filters});setHistory(data||[]);}catch{showToast('Failed to load attendance history','error');}finally{setLoading(false);}};
  const counts=useMemo(()=>({present:history.filter(r=>r.status==='Present').length,absent:history.filter(r=>r.status==='Absent').length,total:history.length}),[history]);
  const update=async()=>{try{await api.put(`/attendance/${edit.record.id}`,{status:edit.status});showToast('Attendance updated.','success');setEdit(null);search();}catch{showToast('Failed to update attendance.','error');}};
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Records</p><h2 className="page-title mt-1">Attendance history</h2><p className="mt-1 text-sm text-slate-500">Find, review and correct previously submitted attendance.</p></div>{history.length>0&&<div className="flex gap-2"><div className="rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>{counts.present} present</div><div className="rounded-xl border border-red-100 bg-red-50 px-3 py-2 text-xs font-semibold text-red-700"><XCircle className="mr-1 inline h-3.5 w-3.5"/>{counts.absent} absent</div></div>}</div>
    <section className="surface p-4 sm:p-5"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-800"><Filter className="h-4 w-4 text-blue-600"/> Filters</div><div className="grid gap-4 md:grid-cols-4"><Select label="Section" value={filters.section_id} onChange={e=>setFilters(v=>({...v,section_id:e.target.value}))} placeholder="All sections" options={sections.map(s=>({value:s.id,label:s.section_name}))}/><Select label="Subject" value={filters.subject_id} onChange={e=>setFilters(v=>({...v,subject_id:e.target.value}))} placeholder="All subjects" options={subjects.map(s=>({value:s.id,label:s.subject_name}))}/><Input type="date" label="Date from" value={filters.date_from} onChange={e=>setFilters(v=>({...v,date_from:e.target.value}))}/><Input type="date" label="Date to" value={filters.date_to} onChange={e=>setFilters(v=>({...v,date_to:e.target.value}))}/></div><div className="mt-4 flex justify-end"><Button icon={Search} loading={loading} onClick={search}>Search records</Button></div></section>
    <section className="surface overflow-hidden">{loading?<div className="flex justify-center py-16"><Spinner/></div>:history.length===0?<div className="py-16 text-center"><HistoryIcon className="mx-auto h-9 w-9 text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-700">No attendance records yet</p><p className="mt-1 text-sm text-slate-500">Choose a section, subject or date range and search.</p></div>:<div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Student</th><th className="px-5 py-3">Subject</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{history.map(r=><tr key={r.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 text-sm text-slate-600"><CalendarDays className="mr-2 inline h-4 w-4 text-slate-400"/>{new Date(r.date).toLocaleDateString()}</td><td className="px-5 py-4"><div className="font-semibold text-slate-800">{r.student_name}</div><div className="text-xs text-slate-500">{r.student_id_code}</div></td><td className="px-5 py-4 text-sm text-slate-600">{r.subject_name}</td><td className="px-5 py-4"><span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold ${r.status==='Present'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{r.status}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>setEdit({record:r,status:r.status})} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-white"><Edit3 className="h-3.5 w-3.5"/> Edit</button></td></tr>)}</tbody></table></div>}</section>
    <ConfirmDialog isOpen={Boolean(edit)} onClose={()=>setEdit(null)} onConfirm={update} title="Update attendance" message={<div className="space-y-3"><p>Choose the new status for <strong>{edit?.record?.student_name}</strong>.</p><div className="flex gap-2"><button type="button" onClick={()=>setEdit(v=>({...v,status:'Present'}))} className={`flex-1 rounded-xl border px-3 py-2 text-sm font-semibold ${edit?.status==='Present'?'border-emerald-500 bg-emerald-50 text-emerald-700':'border-slate-200 text-slate-600'}`}>Present</button><button type="button" onClick={()=>setEdit(v=>({...v,status:'Absent'}))} className={`flex-1 rounded-xl border px-3 py-2 text-sm font-semibold ${edit?.status==='Absent'?'border-red-500 bg-red-50 text-red-700':'border-slate-200 text-slate-600'}`}>Absent</button></div></div>} confirmText="Save change" />
  </div>;
}
